### ISSUE TITLE
DB Service(s) and sync

### ISSUE THREAD

**Issue by niczem** [sea-watch/SAR-Client#1]
Create "parent" dbService which handles the pouchdb instance and returns it to:

1. AuthService
2. VehicleService
3. CaseService

The dbService should also synchronize the db if user is authorized.

Scale sync on client side, let client choose between different sync strategies:
- fast connection (reload often)
- medium connection (reload not so often)
- slow connection (reload rarely)

Do not always sync all objects at all time, but only deltas/changed objects (?)

Auto Scaling with Exponential Backoff (?) - if there is no update for a time interval, increase polling interval exponentially

**Comment by bernd** [comment]
@niczem In one of your emails to the mailing list you wrote:

> The basic Idea is to let the angular application only speak to an offline database (probably pouch) and let the synchronization be handled in a separate process. That way we do not have to deal with any synchronization errors inside the ng2 app.                               
                                                                                 
Is that still the plan and how does this look like?                         
The electron app spawns another process that handles the database sync and offers a HTTP API to the electron app?

**Comment by niczem** [comment]
> Is that still the plan and how does this look like?
> The electron app spawns another process that handles the database sync and offers a HTTP API to the electron app?

If i get it right, pouch is caring about all the synchronization:
https://pouchdb.com/api.html#replication
https://pouchdb.com/api.html#sync

So we don't have to care about it anymore. On the project page(https://pouchdb.com/) they say:

> It enables applications to store data locally while offline, then synchronize it with CouchDB and compatible servers when the application is back online, keeping the user's data in sync no matter where they next login.

And they give the following example:
`var db = new PouchDB('dbname');

db.put({
  _id: 'dave@gmail.com',
  name: 'David',
  age: 69
});

db.changes().on('change', function() {
  console.log('Ch-Ch-Changes');
});

db.replicate.to('http://example.com/mydb');`

So we could init all the databases(vehicles, cases etc) on the clientside inside a wrapper (the dbService) which will be called from the vehicleService, the caseService and so on.

**Comment by cyroxx** [comment]
_From our discussion today:_

We should specify what is expected to happen when two clients change the same model/object attributes in offline mode and only sync with the central DB afterwards. This is most important for Case objects.

Since such conflict resolution logic is crucial to the project, we MUST do proper testing for this part.

**Comment by niczem** [comment]
I moved the messageService as requirement to #14 because it is not essential in the context of this issue
