### ISSUE TITLE
All key-functions are disabled like Copy & Paste

### ISSUE THREAD

**Issue by JoshuaKrueger** [sea-watch/SAR-Client#125]
Doesn't work. Is annoying if I copy for example a position from an external source.

**Comment by JoshuaKrueger** [comment]
It seems to be build problem, because with "npm run electron" everything works for me.

**Comment by niczem** [comment]
just tested it, could it be that you tried to paste strings into number inputs?

**Comment by JoshuaKrueger** [comment]
On MacOS Sierra 10.12.4 (16E195) it works in with npm run electron but not in the builded mac application.
