### ISSUE TITLE
Create new case - Data of field "Additonal information" is not saved

### ISSUE THREAD

**Issue by genovefa** [sea-watch/SAR-Client#128]
Steps:
- Create new case
- Input data in field "additonal information"
- Click on button "Submit"
- Open case again

Issue:
Data of "Additional information" is empty

Expected:
Data of field "Additonal information" should be saved with the other case data

OS: MAC OSX 10.9.5

**Comment by niczem** [comment]
wrong issue decleration in commit message of bc4907f
