### ISSUE TITLE
After create new case, case list overview is not updated

### ISSUE THREAD

**Issue by genovefa** [sea-watch/SAR-Client#129]
Steps:
- Create new case
- Input data 
- Click on button "Submit"

Issue:
In the case list the new created case is not shown. 
Select a filter in the list on the left-hand-side, then the case list is updated and the new case is shown in the list

Expected:
Case list should show the new case in the list of all cases.

OS: MAC OSX 10.9.5

**Comment by JoshuaKrueger** [comment]
Do you have the latest Version installed? Thats sound like an old closed bug. :-)
https://sea-watch.github.io/SAR-Client/
