### ISSUE TITLE
Fallback positioning solution: AIS API

### ISSUE THREAD

**Issue by niczem** [sea-watch/SAR-Client#13]
e.g. Marinetraffic

**Comment by BMP0007** [comment]
Ok assignment me please.

**Comment by BMP0007** [comment]
```
                Document doc = Jsoup.connect("http://www.marinetraffic.com/en/ais/details/ships/shipid:3807251/mmsi:244870698/").get();
                Elements paragraphs = doc.select(".details_data_link");
                for(Element p : paragraphs) {
                    System.out.println(p.text());
```
Output: 
System.out: 34.80522° / 13.67997°

So kann ich in "Android" mit hilfe der JSOUP library auch ohne API die aktuelle Position von MarineTraffic bekommen.

**Comment by JoshuaKrueger** [comment]
Kurzer Einwurf. Die TER-AIS Daten zu bekommen ist nicht das Problem. Wir brauchen SAT-AIS Daten, da TER-AIS noch immer von der Sea-Watch 2 abhängig sind. bspw. Ist jetzt schon wieder unser AIS-Relay nicht am laufen, dadurch kaum Abdeckung im Gebiet.

LG Joshua
