### ISSUE TITLE
created case is not shown on other device

### ISSUE THREAD

**Issue by moeglichsthoeflich** [sea-watch/SAR-Client#135]
Steps:l
login as "onefleet"
create and update a case boat "rubber"  as "possible target" on device. 
use other device, login as "onefleet"
created case is not visible.

expected: 
case should be visible on any device.

Edit case: 2017-05-07T09:17:16.385Z-reportedBy-onefleet
Last updated at 2017-05-08T07:37:36.414Z by onefleet

OS: ubuntu 16.04 (both device)
Mozilla

**Comment by niczem** [comment]
tested. should be fixed
