### ISSUE TITLE
login doesn't work 

### ISSUE THREAD

**Issue by moeglichsthoeflich** [sea-watch/SAR-Client#144]
STEPS:
-I run SAR-Client v0.0.1-beta.8.AppImage
- App-window opens with smaller window "Settings"
- I push "save settings"
- I get information "Settings update successful!"
- I push "OK"; information closes
- App-window is visible with login field

ISSUE:
Login doesn't work

EXPECTED:
login should work

OS: ubuntu 16.04

**Comment by niczem** [comment]
sorry, we changed the password for the database
