### ISSUE TITLE
logout doesn't work

### ISSUE THREAD

**Issue by moeglichsthoeflich** [sea-watch/SAR-Client#148]
Steps:
1. run sar-client 8 App
2. login
3. create case
4. push "logout"

Issue:
logout doesn't work

Expected:
"logout" should work

OS: ubuntu 16.04 
and Windows professional 7.

**Comment by niczem** [comment]
fixed with https://github.com/sea-watch/SAR-Client/commit/f8bdf9365a43c672db0325e198a0892f5652fbd3
