### ISSUE TITLE
Show connection status of client

### ISSUE THREAD

**Issue by niczem** [sea-watch/SAR-Client#16]
...without using traffic (maybe use pouch sync?)

**Comment by cyroxx** [comment]
As far as I understood, we want to check whether we are offline or online. Maybe this is what we are looking for: http://electron.atom.io/docs/tutorial/online-offline-events/

**Comment by niczem** [comment]
Do you know if this method needs additional network traffic?

Another way might be to check if the pouch sync is working well:
https://pouchdb.com/api.html#replication

**Comment by dubbl** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine

"In Chrome and Safari, if the browser is not able to connect to a local area network (LAN) or a router, it is offline; all other conditions return true. So while you can assume that the browser is offline when it returns a false value, you cannot assume that a true value necessarily means that the browser can access the internet."

so no network traffic there, but potentially false positives.

**Comment by niczem** [comment]
False positives wouldn't be that awesome... I would sugges we rely on the pouch service, because if its not replicating, the whole application isn't working anyway.
We should only show messages like "can connect to the server" or "can not connect to the server"
