### ISSUE TITLE
Create Case Report

### ISSUE THREAD

**Issue by niczem** [sea-watch/SAR-Client#161]
- [ ] Create a Button 'Send to MRCC & Backoffices' which creates an automated eMail with the new Case for the MRCC and the Backoffices.

- [ ] Close Case, Create Report & Send Report – To fill in all the report details (Shorted Version of the MRCC Form without details about Origin and intelligence informations (driver etc. pp.) and close the case. Only then Close Case complete. – If not status is only rescued.

**Comment by JoshuaKrueger** [comment]
I have extended something, because that was misunderstood and only with the complete report is the more useful is essential.

**Comment by niczem** [comment]
![img_0575](https://user-images.githubusercontent.com/2991319/27005608-354818fc-4e22-11e7-9d21-304c377d7511.jpg)
![img_0576](https://user-images.githubusercontent.com/2991319/27005609-3563e2a8-4e22-11e7-8152-5812d622c56f.jpg)
![img_0577](https://user-images.githubusercontent.com/2991319/27005610-356c30c0-4e22-11e7-91e4-e51b5b560de3.jpg)
![img_0574](https://user-images.githubusercontent.com/2991319/27005612-3570df8a-4e22-11e7-8339-3b8db96a01e1.jpg)
![img_0573](https://user-images.githubusercontent.com/2991319/27005611-356e86ae-4e22-11e7-9c25-9ef2232bd7be.jpg)
