### ISSUE TITLE
<Navigation> No way back when click in link "leafet" or "seawatch" in footer

### ISSUE THREAD

**Issue by genovefa** [sea-watch/SAR-Client#167]
- open page with map
- click on "leafet" ord "sea-watch" link in footer right hand side

Issue:
Linked page opens, User has no possiblility to go back to SAR Client App

Expected:
Either user has a Back Button on each page or somehow a SAR Client home button.

**Comment by genovefa** [comment]
![map](https://cloud.githubusercontent.com/assets/28511451/26730512/7e0dd0ee-47b1-11e7-9e77-31662e50ada3.jpg)

**Comment by niczem** [comment]
fixed with 1dbe384f7176fce264f8cb89f474392213e975f8
