### ISSUE TITLE
<Login> Proceed without login the user can not see anything except the map

### ISSUE THREAD

**Issue by genovefa** [sea-watch/SAR-Client#170]
- Login page
- Click on link "Proceed without login"

Issue:
- not able to add a case, or to see cases
- no Chat to read
- no boats

Expected Result
Want to be able to create a case and to view

**Comment by genovefa** [comment]
![unregistereduser](https://cloud.githubusercontent.com/assets/28511451/26731851/b0430044-47b5-11e7-937a-7081d82a9bb3.jpg)

**Comment by genovefa** [comment]
hi @niczem @JoshuaKrueger, i am not sure how should be the behaviour be for non registered user ?!

**Comment by niczem** [comment]
@genovefa This is actually a function which can be used if the ship goes offline but the user wants to see the cached data. 
@JoshuaKrueger  does it make sense to change this?

**Comment by niczem** [comment]
added #175 as feature
