### ISSUE TITLE
<Login> No timeout after some time inactivity

### ISSUE THREAD

**Issue by genovefa** [sea-watch/SAR-Client#171]
- login with user credentials
- browsing through the app
- going into the kitchen and cook for some hours
- goto bed and then..

Issue:
User is still logged in and SAR Client is active

Expected:
SAR Client should be locked, User has to login again. (Security reason)

**Comment by genovefa** [comment]
@niczem @JoshuaKrueger not sure if it a bug or a feature, but i found it essential.

**Comment by niczem** [comment]
We need an entry in the settings "Automated Logout after n minutes" which is set to true by default, but it should be possible to disable it on the SAR ships.
