### ISSUE TITLE
Automated Logout after n minutes

### ISSUE THREAD

**Issue by niczem** [sea-watch/SAR-Client#174]
We need an entry in the settings "Automated Logout after n minutes" which is set to true by default, but it should be possible to disable it on the SAR ships.

#171

**Comment by bernd** [comment]
At this time of writing, logging out of the app and logging in again triggers a complete sync - or at least it checks all documents - in PouchDB, pulling >10MB. This might change in the future, but just as a heads up.

**Comment by niczem** [comment]
closed. instead #216
