### ISSUE TITLE
<Navigation> Filter for Vehicles do not show selection

### ISSUE THREAD

**Issue by genovefa** [sea-watch/SAR-Client#178]
- goto map
- vehicles sea-watch2 and moonbird are shown
- select vehicle filter sea-watch2 on the lefthandside navigation bar

issue:
map zoom to sea-watch2, but filter is shown as selected (Radiobutton is not filled)

Expected
Radiobutton of the actual vehicle filter is shown as selected
![vehicels](https://cloud.githubusercontent.com/assets/28511451/26756400/e37468ee-48a1-11e7-8ab9-9dece98fc877.jpg)

**Comment by JoshuaKrueger** [comment]
Actually, a click on this list should only center the boat on the map and where now the gray rings are showing the online statuses of the ships. (Online, Away, Offline). To filter the boats makes in my opinion on the map not any sense.
