### ISSUE TITLE
app is flickering

### ISSUE THREAD

**Issue by moeglichsthoeflich** [sea-watch/SAR-Client#183]
I run beta 14

issue: app screen is flickering 

expected: app sceen should work stable

OS: ubuntu 16.04

**Comment by JoshuaKrueger** [comment]
This bug I honestly do not understand. Can you make it a screenshot or video. ;)

**Comment by bernd** [comment]
I saw this as well, but though it's a problem on my Ubuntu machine. If no one is seeing this on macOS and Windows, it might be related to Linux.

I will try to reproduce it and record it.

**Comment by bernd** [comment]
I was working on the pouchdb issues last week and didn't see the issue anymore. :confused:

**Comment by moeglichsthoeflich** [comment]
I also see it anymore.

**Comment by bernd** [comment]
Okay, cool. :+1:  I will close this issue.
