### ISSUE TITLE
vesselpositions should be individualised on map

### ISSUE THREAD

**Issue by moeglichsthoeflich** [sea-watch/SAR-Client#184]
I run beta 14

Issue:
SW2 and Moonbird are visible as location marker on the map, but only can recognized by pointing on the location marker.

Expected: 
location marker should be individualised by name ("SW2", "Moonbird" etc.) or colour.

**Comment by JoshuaKrueger** [comment]
Color codes do not work on 12 or more ships… 

Here, the icon between ship and plane should be different. Perhaps it would be good you make two ship colors (similar to MarineTraffic) for large rescue ships (Aquarius, VOS H, VOS P etc) and for small (SW2, Iuventa).

**Comment by niczem** [comment]
addded #197
