### ISSUE TITLE
<Navigation> Default Search function is not aktiv 

### ISSUE THREAD

**Issue by genovefa** [sea-watch/SAR-Client#187]
- Press menu button "cases"
- Want to search for a number in the case list
- press strg+f or apfel+f

issue:
after press strg+f or apfel+f no search field appears

expected
user should be able to search for pattern, so that he can find easily a case in the list

**Comment by JoshuaKrueger** [comment]
@niczem: Is this maybe a solution? https://github.com/rhysd/electron-in-page-search
