### ISSUE TITLE
create case: longitude: inputfield too small

### ISSUE THREAD

**Issue by moeglichsthoeflich** [sea-watch/SAR-Client#191]
steps:
I open formular "create case"
I want to fill in numbers in "longitude"

issue:
fields are too small for inserting numbers. selecting numbers is also not possible

expected: 
longitude fields should be able to contain two numbers each.

OS: ubuntu 16.04

**Comment by niczem** [comment]
can you add a screenshot?

**Comment by JoshuaKrueger** [comment]
![bildschirmfoto 2017-06-08 um 20 48 35](https://user-images.githubusercontent.com/6384994/26945405-eacda180-4c8b-11e7-8f67-c3a5967b31c5.png)

**Comment by niczem** [comment]
fixed with  d06f29f
