### ISSUE TITLE
Map: Position does not update

### ISSUE THREAD

**Issue by JoshuaKrueger** [sea-watch/SAR-Client#195]
After a day break open the app – Positions of yesterday. After reinitialize the DB, reopening (#194) the app, new positions shown.

After: I watch now for 20 Minutes and nothing happen on the map. Second screen: MarineTraffic – Ships are moving. 

Position Updating does not work everytime.

-----
MacBook Pro (Retina 13 Zoll, Anfang 2015)
MacOS 10.12.4 (16E195)

**Comment by niczem** [comment]
It can take up to 60s until the new positions are shown.
