### ISSUE TITLE
AuthService and Login

### ISSUE THREAD

**Issue by niczem** [sea-watch/SAR-Client#2]
Implement authService
- [x] login(username, password) - Log in an existing user
- [x] getUser() - return userinfo of current user.

Implement Login and show login on startup if no session exists.

- How do we proceed in case of no network connection on startup?

**Comment by bernd** [comment]
I have no idea how pouchdb works, but I guess the very first startup of the app needs internet connection to do an initial login to the backend and to fetch some initial data. Once the app has some kind of authentication token or session, the sync with the main database can happen without login once the internet connection is restored.

**Comment by niczem** [comment]
I used [this](https://github.com/nolanlawson/pouchdb-authentication) plugin so far.

In the documentation they have different "CouchDB authentication recipes". I think we either need to orientate on the "[some-people-can-read-some-docs-some-people-can-write-those-same-docs](https://github.com/nolanlawson/pouchdb-authentication#some-people-can-read-some-docs-some-people-can-write-those-same-docs)"- or the "[everybody-has-to-be-logged-in-to-do-anything](https://github.com/nolanlawson/pouchdb-authentication#everybody-has-to-be-logged-in-to-do-anything)" recipe.

In the first receipe the following design is suggested:

> The standard practice for this is to set up one database per user. Don't be scared: databases are cheap, and Cloudant says 100k databases per account is not uncommon.

Does this make sense to you and do you have an idea how to build a design for vehicles and cases with that?
