### ISSUE TITLE
map: button at right corner is not visible completely

### ISSUE THREAD

**Issue by moeglichsthoeflich** [sea-watch/SAR-Client#206]
## Environment

- App version: beta 16
- Operating System: Ubuntu 16.04

## Issue
button above button "layers" (map: right above corner) is only partly visible (s. image) 

## Steps to Reproduce

1. run the app, login
2.  open the map
![bildschirmfoto_2017-06-28_14-43-42](https://user-images.githubusercontent.com/28480344/27637552-6c5f32c0-5c10-11e7-9b20-4b0629d63644.png)

## Expected
both buttons on the map should be visible.

**Comment by niczem** [comment]
should be fixed with bb2ab41
