### ISSUE TITLE
Roboto font usage

### ISSUE THREAD

**Issue by bernd** [sea-watch/SAR-Client#42]
In #38 we removed the Roboto remote font from the `src/css/site.css`.

Grepping for the font, it looks like it is actually in use. 

```
$ git grep -i roboto
src/app/components/create-case-form/create-case-form.component.css:  font-family: roboto;
src/app/components/log-in/log-in.component.css:@import url(http://fonts.googleapis.com/css?family=Roboto);
src/app/components/log-in/log-in.component.css:  font-family: roboto;
src/app/components/log-in/log-in.component.css:  font-family: roboto;
src/app/components/log-in/log-in.component.css:  font-family: roboto;
src/css/site.css:  font-family: "Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;
src/css/site.css:  font-family: "Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;
```

 Is this an issue? /cc @niczem @JoshuaKrueger

**Comment by bernd** [comment]
Heh, we also still have a remote font usage in `src/app/components/log-in/log-in.component.css`. :smile:

**Comment by niczem** [comment]
Damn :D I'll just replace it with helvetica if @JoshuaKrueger is okay with that.

**Comment by JoshuaKrueger** [comment]
Hey, Just use the system font like wordpress and then use Helvetica as a fallback.

"-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif;“
