### ISSUE TITLE
pouchdb persistance - retry if offline

### ISSUE THREAD

**Issue by JoshuaKrueger** [sea-watch/SAR-Client#62]
If client is offline during case creation, retry if connection is back.

Links:
https://github.com/pouchdb/pouchdb/issues/966

**Comment by niczem** [comment]
fixed with: [91a2279d9c2f8a34008be3a08528a0a7e971d423](https://github.com/sea-watch/SAR-Client/commit/91a2279d9c2f8a34008be3a08528a0a7e971d423)
