### ISSUE TITLE
Question about pouchdb usage patterns

### ISSUE THREAD

**Issue by bernd** [sea-watch/SAR-Client#89]
While working on #85 I read through some of the other code as well and noticed some pouchdb usage patterns I don't understand.

In `PouchService#initDB()` we set up a sync replication between the local pouchdb and the remote CouchDB instance. That totally makes sense because we want to keep both databases in sync.
We also propagate changes to all registered remote change listeners to allow live updates in the UI. (e.g. the case creation/edit form)
Now the thing I don't understand yet: In `PouchService#get()` we subscribe to the changes feed of the database and maintain a `data` array to keep track of the contents of the database.

Why are we maintaining the contents of the database inside the PouchService instance? As far as I understand pouchdb, after reading its documentation, we should always ask the local pouchdb if we need the data. There should be no need to have another "caching layer" for the data on top of that.

Also when looking at the VehiclesService and SettingsService, it looks like they duplicate some of the logic in `PouchService#get()`. They set up a changes feed to update the cached data inside the PouchService. Not sure why.

Is there anything I am missing? Is there a reason why we go through the hassle of maintaining copies of the data in memory?

/cc @niczem @koop-bremen

**Comment by niczem** [comment]
You are right it was used as a caching layer inside the pouchService.

And I think its obsolete, it is only used inside the vehicles services which hasn't been updated after the syncing function inside the pouchService.initDb() has been changed:

```
return new Promise(resolve => {

      this.db.allDocs({

        include_docs: true

      }).then((result) => {

        this.data = [];

        let docs = result.rows.map((row) => {
          this.data.push(row.doc);
        });

        resolve(this.data);

        this.db.changes({ live: true, since: 'now', include_docs: true }).on('change', (change) => {
          this.pouchService.handleChange('vehicles', change);
        });

      }).catch((error) => {

        console.log(error);

      });

    });
```
can be shortened to

  ```
getVehicles() {
      return this.pouchService.get('vehicles');
}
```
then the data var and the handleChanges function can be removed from the pouchService, right?

**Comment by bernd** [comment]
> Then the data var and the handleChanges function can be removed from the pouchService, right?

As far as I can see, yes. When we get all data from pouchdb all the time, we don't need to cache the data inside the services.

**Comment by bernd** [comment]
Closing this, https://github.com/sea-watch/SAR-Client/pull/205 will introduce a new PouchDB database layer.
